### ISSUE TITLE
Repository link?

### ISSUE THREAD

**Issue by casperse** [hotio/whisparr#1]
`Hi.

I am using both the old and the new version.
But it seems the old version is removed from:
cr.hotio.dev/hotio/whisparr:v1

Is there any other repository for this build?

**Comment by casperse** [comment]
on docker.io

**Comment by retardedboy** [comment]
having the same issue, did you ever find the v1 image?

**Comment by mrhotio** [comment]
use discord for support...like he said, on docker hub
