### ISSUE TITLE
Add more indexers

### ISSUE THREAD

**Issue by thany** [hotio/whisparr#5]
I'm not sure if there are any super strict requirements on indexers, but I understand they are a vital component into getting whisparr to do anything beyond listing episodes I do or don't have, iow, to download missing ones.

As for FileList, HDBits, and IP Torrents:

These indexers are all ones that require a login but do not provide any means of registering for a login. Not whisparr's fault of course, but it's kind of weird, to say the least, to include only those and not add public ones that anyone can use. Ones like, oh I dunno, limetorrents or rargb or something. Take a pick, there are (still) dozens.

As for Torrent RSS Feed

This doesn't seem like a specific site. Where do I get a "Full RSS Feed URL"? No explanation is provided. An example would go a long way.

As for Torznab

What is this even? Where do I get the URL and API key for it? I can't find such site anywhere, let alone getting logged into it.

**Comment by engels74** [comment]
> I'm not sure if there are any super strict requirements on indexers, but I understand they are a vital component into getting whisparr to do anything beyond listing episodes I do or don't have, iow, to download missing ones.
> 
> As for FileList, HDBits, and IP Torrents:
> 
> These indexers are all ones that require a login but do not provide any means of registering for a login. Not whisparr's fault of course, but it's kind of weird, to say the least, to include only those and not add public ones that anyone can use. Ones like, oh I dunno, limetorrents or rargb or something. Take a pick, there are (still) dozens.
> 
> As for Torrent RSS Feed
> 
> This doesn't seem like a specific site. Where do I get a "Full RSS Feed URL"? No explanation is provided. An example would go a long way.
> 
> As for Torznab
> 
> What is this even? Where do I get the URL and API key for it? I can't find such site anywhere, let alone getting logged into it.

You are requesting in the wrong repository. This is an unofficial Docker image for Whisparr, not the actual repository for the project.

Also to answer your request - use Prowlarr, it has support for basically all your mentioned indexers.
